# Generated by Django 5.1.1 on 2024-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_post',
        ),
    ]
